### ISSUE TITLE
Unable to create destination storage account

### ISSUE THREAD

**Issue by KobusOlie4** [JeffBow/AzurePowerShell#8] opened 2017-07-13 16:02 UTC
When I need to create the destination storage account - it keeps failing:

New-AzureRmStorageAccount : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or 
empty, and then try the command again.

$newStorageAccount = New-AzureRmStorageAccount $storageParams -e ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzureRmStorageAccount], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Management.Storage.NewAzureStorageAccountCommand

**Comment by JeffBow** [comment] 2017-07-17 19:05
@KobusOlie4   Which script were you running and what version of the AzureRM.Storage module do you have?  Use Get-Command New-AzureRmStorageAccount to verify you have version 2.3 or higher.  I did notice the newer module versions use -Name instead of -AccountName, but I've verified with both version 2.3 and 3.2 that it works with either parameter name.  I suspect since your -Name parameter is null, the storage account you're trying to clone is empty or does not have any storage blobs.  These scripts have not been modified to work with Managed Disks yet and rely on the URI of the blob storage to get the details of the source storage account. HTH and thanks for the feedback.

**Comment by KobusOlie4** [comment] 2017-07-17 19:11
Thank you Jeff, REALLY cool script – I will test tomorrow morning again and revert.

Regards
Kobus

**Comment by JeffBow** [comment] 2017-08-01 02:03
@KobusOlie4  I confirmed it is the newer modules causing this problem.  AzureRM version 3.2 used AccountName, but now that property is just Name in 4.2.1. This has been resolved in the latest release.

**Closed as completed by JeffBow** 2017-08-01 02:03 UTC
